def find_differences(list1, list2):
    # Ensure both lists are of the same length
    if len(list1) != len(list2):
        raise ValueError("Lists must be of the same length")

    # Iterate over the lists and compare elements
    count_diff = 0
    for i in range(len(list1)):
        if list1[i] != list2[i]:
            count_diff += 1
    return count_diff

#Below are the amino acid cytochrome c lists for different animals
human =           ['G', 'D', 'V', 'E', 'K', 'G', 'K', 'K', 'I', 'F', 'I', 'M', 'K', 'C', 'S', 'Q', 'C', 'H', 'T', 'V', 'E', 'K', 'G', 'G', 'K', 'G', 'K', 'T', 'G', 'P', 'N', 'L', 'H', 'G', 'L', 'F', 'G', 'R', 'K', 'T', 'G', 'Q', 'A', 'P', 'G', 'Y', 'S', 'Y', 'T', 'A', 'A', 'N', 'K', 'N', 'K', 'G', 'I', 'I', 'W', 'G', 'E', 'D', 'T', 'L', 'M', 'E', 'Y', 'L', 'E', 'N', 'P', 'K', 'K', 'Y', 'I', 'P', 'G', 'T', 'K', 'M', 'I', 'F', 'V', 'G', 'I', 'K', 'K', 'K', 'E', 'E', 'R', 'A', 'D', 'L', 'I', 'A', 'Y', 'L', 'K', 'K', 'A', 'T', 'N', 'E']
rhesus_monkey =   ['G', 'D', 'V', 'E', 'K', 'G', 'K', 'K', 'I', 'F', 'I', 'M', 'K', 'C', 'S', 'Q', 'C', 'H', 'T', 'V', 'E', 'K', 'G', 'G', 'K', 'G', 'K', 'T', 'G', 'P', 'N', 'L', 'H', 'G', 'L', 'F', 'G', 'R', 'K', 'T', 'G', 'Q', 'A', 'P', 'G', 'Y', 'S', 'Y', 'T', 'A', 'A', 'N', 'K', 'N', 'K', 'G', 'I', 'T', 'W', 'G', 'E', 'D', 'T', 'L', 'M', 'E', 'Y', 'L', 'E', 'N', 'P', 'K', 'K', 'Y', 'I', 'P', 'G', 'T', 'K', 'M', 'I', 'F', 'V', 'G', 'I', 'K', 'K', 'K', 'E', 'E', 'R', 'A', 'D', 'L', 'I', 'A', 'Y', 'L', 'K', 'K', 'A', 'T', 'N', 'E']
horse =           ['G', 'D', 'V', 'E', 'K', 'G', 'K', 'K', 'I', 'F', 'V', 'Q', 'K', 'C', 'A', 'Q', 'C', 'H', 'T', 'V', 'E', 'K', 'G', 'G', 'K', 'G', 'K', 'T', 'G', 'P', 'N', 'L', 'H', 'G', 'L', 'F', 'G', 'R', 'K', 'T', 'G', 'Q', 'A', 'P', 'G', 'F', 'T', 'Y', 'T', 'D', 'A', 'N', 'K', 'N', 'K', 'G', 'I', 'T', 'W', 'K', 'E', 'E', 'T', 'L', 'M', 'E', 'Y', 'L', 'E', 'N', 'P', 'K', 'K', 'Y', 'I', 'P', 'G', 'T', 'K', 'M', 'I', 'F', 'A', 'G', 'I', 'K', 'K', 'K', 'T', 'E', 'R', 'E', 'D', 'L', 'I', 'A', 'Y', 'L', 'K', 'K', 'A', 'T', 'N', 'E']
pig =             ['G', 'D', 'V', 'E', 'K', 'G', 'K', 'K', 'I', 'F', 'V', 'Q', 'K', 'C', 'A', 'Q', 'C', 'H', 'T', 'V', 'E', 'K', 'G', 'G', 'K', 'G', 'K', 'T', 'G', 'P', 'N', 'L', 'H', 'G', 'L', 'F', 'G', 'R', 'K', 'T', 'G', 'Q', 'A', 'P', 'G', 'F', 'S', 'Y', 'T', 'D', 'A', 'N', 'K', 'N', 'K', 'G', 'I', 'T', 'W', 'G', 'E', 'E', 'T', 'L', 'M', 'E', 'Y', 'L', 'E', 'N', 'P', 'K', 'K', 'Y', 'I', 'P', 'G', 'T', 'K', 'M', 'I', 'F', 'A', 'G', 'I', 'K', 'K', 'K', 'G', 'E', 'R', 'E', 'D', 'L', 'I', 'A', 'Y', 'L', 'K', 'K', 'A', 'T', 'N', 'E']
cow =             ['G', 'D', 'V', 'E', 'K', 'G', 'K', 'K', 'I', 'F', 'V', 'Q', 'K', 'C', 'A', 'Q', 'C', 'H', 'T', 'V', 'E', 'K', 'G', 'G', 'K', 'G', 'K', 'T', 'G', 'P', 'N', 'L', 'H', 'G', 'L', 'F', 'G', 'R', 'K', 'T', 'G', 'Q', 'A', 'P', 'G', 'F', 'S', 'Y', 'T', 'D', 'A', 'N', 'K', 'N', 'K', 'G', 'I', 'T', 'W', 'G', 'E', 'E', 'T', 'L', 'M', 'E', 'Y', 'L', 'E', 'N', 'P', 'K', 'K', 'Y', 'I', 'P', 'G', 'T', 'K', 'M', 'I', 'F', 'A', 'G', 'I', 'K', 'K', 'K', 'G', 'E', 'R', 'E', 'D', 'L', 'I', 'A', 'Y', 'L', 'K', 'K', 'A', 'T', 'N', 'E']
sheep =           ['G', 'D', 'V', 'E', 'K', 'G', 'K', 'K', 'I', 'F', 'V', 'Q', 'K', 'C', 'A', 'Q', 'C', 'H', 'T', 'V', 'E', 'K', 'G', 'G', 'K', 'G', 'K', 'T', 'G', 'P', 'N', 'L', 'H', 'G', 'L', 'F', 'G', 'R', 'K', 'T', 'G', 'Q', 'A', 'P', 'G', 'F', 'S', 'Y', 'T', 'D', 'A', 'N', 'K', 'N', 'K', 'G', 'I', 'T', 'W', 'G', 'E', 'E', 'T', 'L', 'M', 'E', 'Y', 'L', 'E', 'N', 'P', 'K', 'K', 'Y', 'I', 'P', 'G', 'T', 'K', 'M', 'I', 'F', 'A', 'G', 'I', 'K', 'K', 'K', 'G', 'E', 'R', 'E', 'D', 'L', 'I', 'A', 'Y', 'L', 'K', 'K', 'A', 'T', 'N', 'E']
dog =             ['G', 'D', 'V', 'E', 'K', 'G', 'K', 'K', 'I', 'F', 'V', 'Q', 'K', 'C', 'A', 'Q', 'C', 'H', 'T', 'V', 'E', 'K', 'G', 'G', 'K', 'G', 'K', 'T', 'G', 'P', 'N', 'L', 'H', 'G', 'L', 'F', 'G', 'R', 'K', 'T', 'G', 'Q', 'A', 'P', 'G', 'F', 'S', 'Y', 'T', 'D', 'A', 'N', 'K', 'N', 'K', 'G', 'I', 'T', 'W', 'G', 'E', 'E', 'T', 'L', 'M', 'E', 'Y', 'L', 'E', 'N', 'P', 'K', 'K', 'Y', 'I', 'P', 'G', 'T', 'K', 'M', 'I', 'F', 'A', 'G', 'I', 'K', 'K', 'T', 'G', 'E', 'R', 'A', 'D', 'L', 'I', 'A', 'Y', 'L', 'K', 'K', 'A', 'T', 'K', 'E']
gray_whale =      ['G', 'D', 'V', 'E', 'K', 'G', 'K', 'K', 'I', 'F', 'V', 'Q', 'K', 'C', 'A', 'Q', 'C', 'H', 'T', 'V', 'E', 'K', 'G', 'G', 'K', 'G', 'K', 'T', 'G', 'P', 'N', 'L', 'H', 'G', 'L', 'F', 'G', 'R', 'K', 'T', 'G', 'Q', 'A', 'V', 'G', 'F', 'S', 'Y', 'T', 'D', 'A', 'N', 'K', 'N', 'K', 'G', 'I', 'T', 'W', 'G', 'E', 'E', 'T', 'L', 'M', 'E', 'Y', 'L', 'E', 'N', 'P', 'K', 'K', 'Y', 'I', 'P', 'G', 'T', 'K', 'M', 'I', 'F', 'A', 'G', 'I', 'K', 'K', 'K', 'G', 'E', 'R', 'A', 'D', 'L', 'I', 'A', 'Y', 'L', 'K', 'K', 'A', 'T', 'N', 'E']
rabbit =          ['G', 'D', 'V', 'E', 'K', 'G', 'K', 'K', 'I', 'F', 'V', 'Q', 'K', 'C', 'A', 'Q', 'C', 'H', 'T', 'V', 'E', 'K', 'G', 'G', 'K', 'G', 'K', 'T', 'G', 'P', 'N', 'L', 'H', 'G', 'L', 'F', 'G', 'R', 'K', 'T', 'G', 'Q', 'A', 'V', 'G', 'F', 'S', 'Y', 'T', 'D', 'A', 'N', 'K', 'N', 'K', 'G', 'I', 'T', 'W', 'G', 'E', 'D', 'T', 'L', 'M', 'E', 'Y', 'L', 'E', 'N', 'P', 'K', 'K', 'Y', 'I', 'P', 'G', 'T', 'K', 'M', 'I', 'F', 'A', 'G', 'I', 'K', 'K', 'K', 'D', 'E', 'R', 'A', 'D', 'L', 'I', 'A', 'Y', 'L', 'K', 'K', 'A', 'T', 'N', 'E']
kangaroo =        ['G', 'D', 'V', 'E', 'K', 'G', 'K', 'K', 'I', 'F', 'V', 'Q', 'K', 'C', 'A', 'Q', 'C', 'H', 'T', 'V', 'E', 'K', 'G', 'G', 'K', 'G', 'K', 'T', 'G', 'P', 'N', 'L', 'H', 'G', 'I', 'F', 'G', 'R', 'K', 'T', 'G', 'Q', 'A', 'P', 'G', 'F', 'T', 'Y', 'T', 'D', 'A', 'N', 'K', 'N', 'K', 'G', 'I', 'I', 'W', 'G', 'E', 'D', 'T', 'L', 'M', 'E', 'Y', 'L', 'E', 'N', 'P', 'K', 'K', 'Y', 'I', 'P', 'G', 'T', 'K', 'M', 'I', 'F', 'A', 'G', 'I', 'K', 'K', 'K', 'G', 'E', 'R', 'A', 'D', 'L', 'I', 'A', 'Y', 'L', 'K', 'K', 'A', 'T', 'N', 'E']
chicken =         ['G', 'D', 'I', 'E', 'K', 'G', 'K', 'K', 'I', 'F', 'V', 'Q', 'K', 'C', 'S', 'Q', 'C', 'H', 'T', 'V', 'E', 'K', 'G', 'G', 'K', 'G', 'K', 'T', 'G', 'P', 'N', 'L', 'H', 'G', 'L', 'F', 'G', 'R', 'K', 'T', 'G', 'Q', 'A', 'E', 'G', 'F', 'S', 'Y', 'T', 'D', 'A', 'N', 'K', 'N', 'K', 'G', 'I', 'T', 'W', 'G', 'E', 'D', 'T', 'L', 'M', 'E', 'Y', 'L', 'E', 'N', 'P', 'K', 'K', 'Y', 'I', 'P', 'G', 'T', 'K', 'M', 'I', 'F', 'A', 'G', 'I', 'K', 'K', 'K', 'S', 'E', 'R', 'V', 'D', 'L', 'I', 'A', 'Y', 'L', 'K', 'D', 'A', 'T', 'S', 'K']
my_list =         ['G', 'D', 'I', 'E', 'K', 'G', 'K', 'K', 'I', 'F', 'V', 'Q', 'K', 'C', 'S', 'Q', 'C', 'H', 'T', 'V', 'E', 'K', 'G', 'G', 'K', 'G', 'K', 'T', 'G', 'P', 'N', 'L', 'H', 'G', 'I', 'F', 'G', 'R', 'K', 'T', 'G', 'Q', 'A', 'E', 'G', 'F', 'S', 'Y', 'T', 'D', 'A', 'N', 'K', 'N', 'K', 'G', 'I', 'T', 'W', 'G', 'E', 'D', 'T', 'L', 'M', 'E', 'Y', 'L', 'E', 'N', 'P', 'K', 'K', 'Y', 'I', 'P', 'G', 'T', 'K', 'M', 'I', 'F', 'A', 'G', 'I', 'K', 'K', 'K', 'S', 'E', 'R', 'A', 'D', 'L', 'I', 'A', 'Y', 'L', 'K', 'D', 'A', 'T', 'S', 'K']
pekin_duck =      ['G', 'D', 'V', 'E', 'K', 'G', 'K', 'K', 'I', 'F', 'V', 'Q', 'K', 'C', 'S', 'Q', 'C', 'H', 'T', 'V', 'E', 'K', 'G', 'G', 'K', 'G', 'K', 'T', 'G', 'P', 'N', 'L', 'H', 'G', 'L', 'F', 'G', 'R', 'K', 'T', 'G', 'Q', 'A', 'E', 'G', 'F', 'S', 'Y', 'T', 'D', 'A', 'N', 'K', 'N', 'K', 'G', 'I', 'T', 'W', 'G', 'E', 'D', 'T', 'L', 'M', 'E', 'Y', 'L', 'E', 'N', 'P', 'K', 'K', 'Y', 'I', 'P', 'G', 'T', 'K', 'M', 'I', 'F', 'A', 'G', 'I', 'K', 'K', 'K', 'S', 'E', 'R', 'A', 'D', 'L', 'I', 'A', 'Y', 'L', 'K', 'D', 'A', 'T', 'A', 'K']
snapping_turtle = ['G', 'D', 'V', 'E', 'K', 'G', 'K', 'K', 'I', 'F', 'V', 'Q', 'K', 'C', 'A', 'Q', 'C', 'H', 'T', 'V', 'E', 'K', 'G', 'G', 'K', 'G', 'K', 'T', 'G', 'P', 'N', 'L', 'H', 'G', 'L', 'I', 'G', 'R', 'K', 'T', 'G', 'Q', 'A', 'E', 'G', 'F', 'S', 'Y', 'T', 'E', 'A', 'N', 'K', 'N', 'K', 'G', 'I', 'T', 'W', 'G', 'E', 'E', 'T', 'L', 'M', 'E', 'Y', 'L', 'E', 'N', 'P', 'K', 'K', 'Y', 'I', 'P', 'G', 'T', 'K', 'M', 'I', 'F', 'A', 'G', 'I', 'K', 'K', 'K', 'A', 'E', 'R', 'A', 'D', 'L', 'I', 'A', 'Y', 'L', 'K', 'D', 'A', 'T', 'S', 'K']
bullfrog =        ['G', 'D', 'V', 'E', 'K', 'G', 'K', 'K', 'I', 'F', 'V', 'Q', 'K', 'C', 'A', 'Q', 'C', 'H', 'T', 'C', 'E', 'K', 'G', 'G', 'K', 'G', 'K', 'V', 'G', 'P', 'N', 'L', 'Y', 'G', 'L', 'I', 'G', 'R', 'K', 'T', 'G', 'Q', 'A', 'A', 'G', 'F', 'S', 'Y', 'T', 'D', 'A', 'N', 'K', 'N', 'K', 'G', 'I', 'T', 'W', 'G', 'E', 'D', 'T', 'L', 'M', 'E', 'Y', 'L', 'E', 'N', 'P', 'K', 'K', 'Y', 'I', 'P', 'G', 'T', 'K', 'M', 'I', 'F', 'A', 'G', 'I', 'K', 'K', 'K', 'G', 'E', 'R', 'Q', 'D', 'L', 'I', 'A', 'Y', 'L', 'K', 'S', 'A', 'C', 'S', 'K']
penguin =         ['G', 'D', 'I', 'E', 'K', 'G', 'K', 'K', 'I', 'F', 'V', 'Q', 'K', 'C', 'S', 'Q', 'C', 'H', 'T', 'V', 'E', 'K', 'G', 'G', 'K', 'G', 'K', 'T', 'G', 'P', 'N', 'L', 'H', 'G', 'I', 'F', 'G', 'R', 'K', 'T', 'G', 'Q', 'A', 'E', 'G', 'F', 'S', 'Y', 'T', 'D', 'A', 'N', 'K', 'N', 'K', 'G', 'I', 'T', 'W', 'G', 'E', 'D', 'T', 'L', 'M', 'E', 'Y', 'L', 'E', 'N', 'P', 'K', 'K', 'Y', 'I', 'P', 'G', 'T', 'K', 'M', 'I', 'F', 'A', 'G', 'I', 'K', 'K', 'K', 'S', 'E', 'R', 'A', 'D', 'L', 'I', 'A', 'Y', 'L', 'K', 'D', 'A', 'T', 'S', 'K']

print("Welcome this tool compares the amino acid cytochrome c of different animals ")
list1 = input("What is the first animal you'd like to compare: ")
list2 = input("What is the second animal you'd like to compare: ")

result = find_differences(list1, list2)
print(f'The number of differences between the amino acid cytochrome c of {str(list1)} and {str(list2)}: {result}.')

print(len(human) == len(snapping_turtle))